---
title: "Business_Analysis"
author: "Ifeoluwa Ruth Olonijolu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading of Libraries
```{r loading libraries}
library(tidyverse)
library(readxl)
```

# data importing, Cleaning and Preprocessing

```{r}
rep_13 <- read_excel("~/Documents/Dolapo/new/ore/rep_13.xlsx")
ev_13 <- read_excel("~/Documents/Dolapo/new/ore/ev_13.xlsx")

summary(rep_13)
summary(ev_13)
names(rep_13)

### Cleaning data : consistency, removal of outlier done in excel
### dropping rows with NA's
ev_13 <- ev_13[complete.cases(ev_13), ]

## droping variable training in rep_13 dataset has it contains alot of missing rows
rep_13 <- rep_13[, -which(names(rep_13) == "training")]

###Merging clean 
marged_Data <- merge.data.frame(ev_13, rep_13, by = "rep_id")
dim(marged_Data)

## Proper variable type
#marged_Data$period <- as.character(marged_Data$period, levels=c(1,2,3,4,5,6,7,8,9,10,11,12))

#marged_Data$experience <- as.character(marged_Data$experience)

summary(marged_Data)

names(marged_Data)
```

# Visualisation
```{r}
variable_1 = c("commissions","marketing","purchase" )
variable_2 = c("product" , "campaign")
variable_3 = c("jobtype","qualification", "gender","experience")

for (j in variable_2) {
  for (i in variable_1) {
    p <- ggplot(marged_Data, aes(x = period, y = .data[[i]])) +
      geom_point() +
      facet_wrap(. ~ .data[[j]])
    print(p)
  }
}
  
```


## Regression Model
```{r}
model_Prod <- lm(purchase ~ marketing +product+ promotions + buyer + campaign + jobtype + qualification + gender + experience, data = marged_Data )

summary(model_Prod)
```


